namespace BlacksmithCore.Infra.Attributes.Profession
{
    /// <summary>
    /// Generated by ModifierBindingGenerator Phase 1.
    /// Marks one private member of a MainProfession that should be exposed
    /// to ProfessionModifier subclasses. Applied per-member (AllowMultiple).
    /// Phase 2 reads these from the compiled DLL to generate cross-project bindings.
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    public class BindingContractAttribute : Attribute
    {
        public string MemberName { get; }
        public string TypeFullName { get; }
        /// <summary>true = field, false = property.</summary>
        public bool IsField { get; }
        /// <summary>For fields: IsReadonly. For properties: HasSetter.</summary>
        public bool Flag { get; }

        public BindingContractAttribute(string memberName, string typeFullName, bool isField, bool flag)
        {
            MemberName = memberName;
            TypeFullName = typeFullName;
            IsField = isField;
            Flag = flag;
        }
    }
}
